# Generated by Django 4.2.7 on 2026-05-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='score',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='bad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='caixa_alta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='confianca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='hate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='middlelist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='nice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='score_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='solida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='api_comment',
        ),
    ]
