# Generated by Django 4.2.7 on 2026-05-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_comment_created_at_remove_comment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
