# Generated by Django 4.2.7 on 2026-06-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('hate', models.BooleanField(default=False)),
                ('bad', models.BooleanField(default=False)),
                ('nice', models.BooleanField(default=False)),
                ('solida', models.BooleanField(default=False)),
                ('caixa_alta', models.BooleanField(default=False)),
                ('spam', models.BooleanField(default=False)),
                ('middlelist', models.BooleanField(default=False)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('confianca', models.FloatField(default=0.0)),
                ('score_p', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'test_comments',
            },
        ),
    ]
