import re as regex

from .remover_acento import remover_acentos
def check_hate(text: str) -> bool:
    # Palavras de ataque a minorias (racismo, homofobia, etc.)
    text = remover_acentos(text.lower())
    hate_keywords = [
        "aberracao",
        "bahiano",
        "baianagem",
        "baiano",
        "baitola",
        "baleia",
        "bambi",
        "biba",
        "bicha",
        "bichinha",
        "bichona",
        "bixa",
        "bixinha",
        "bixona",
        "boiola",
        "bolsominion",
        "bolsonazista",
        "bombom",
        "bombril",
        "bozo",
        "bugre",
        "cabeca chata",
        "cabelo ruim",
        "carioca",
        "carvao",
        "cheiro de preto",
        "chimpanze",
        "chinesinho",
        "comunista",
        "corrupto",
        "criola",
        "criolo",
        "crioula",
        "crioulo",
        "cuzao",
        "dike",
        "doente",
        "escravinho",
        "escravo",
        "escurinha",
        "escurinho",
        "esquerdopata",
        "facista",
        "fascista",
        "favela",
        "favelado",
        "fedido",
        "feminazi",
        "feministo",
        "flor",
        "florzinha",
        "gayzao",
        "globalista",
        "gorda",
        "gorila",
        "gringo",
        "ideologia de genero",
        "indio",
        "invertido",
        "japinha",
        "judeu",
        "ladrao",
        "lesbica",
        "lulopetista",
        "macaca",
        "macaco",
        "machista",
        "marica",
        "militante",
        "mineiro",
        "mongoloide",
        "monstro",
        "mulherzinha",
        "nazi",
        "nega",
        "negao",
        "neguinha",
        "neguinho",
        "nordestino",
        "olavista",
        "onca",
        "paneleiro",
        "paraiba",
        "paulista",
        "petista",
        "petralha",
        "piranha",
        "piriguete",
        "pixaim",
        "pretinha",
        "pretinho",
        "preto",
        "primitivo",
        "puta",
        "putinha",
        "redpill",
        "retardado",
        "sapatao",
        "selvagem",
        "sulista",
        "tisil",
        "transviado",
        "traveco",
        "travesti",
        "turco",
        "vaca",
        "vadia",
        "vagaba",
        "vagabunda",
        "veadao",
        "veadinho",
        "veado",
        "viadao",
        "viadinho",
        "viado",
        "xing ling",
        "xing-ling",
        "xingling"
    ]
        # Verifica cada palavra da lista usando Regex para casar apenas a palavra inteira
    for word in hate_keywords:
        # \b cria uma "fronteira", garantindo que "cu" só dê match se estiver isolado
        padrao = rf'\b{word}\b'
        if regex.search(padrao, text):
            return True
            
    return False