def check_middle(text: str) -> bool:
    # Palavrões de intensificação (puta, foda, caralho)
    middle_keywords = [
        "bagulho",
        "caceta",
        "cacete",
        "caralhada",
        "caralho",
        "caralhos",
        "desgraca",
        "do cacete",
        "do cao",
        "do caralho",
        "do inferno",
        "filho da puta",
        "filhodaputa",
        "foda",
        "foda-se",
        "fodase",
        "fodastico",
        "fodido",
        "krl",
        "merda",
        "pica",
        "porra",
        "pqp",
        "pra caralho",
        "puta merda",
        "puta que o pariu",
        "puta que pariu",
        "puta",
        "putaria",
        "puto",
        "que merda",
        "que porra e essa",
        "que porra",
        "ta foda",
        "ta porra",
        "vai se foder",
        "vai tomar no cu",
        "vtnc"
    ]
    return any(word in text.lower() for word in middle_keywords)