def check_solida(text: str) -> bool:
    # apoio geral (ótimo, excelente, maravilhoso)
    solida_keywords = [
        "tamo junto",
        "tmj",
        "bora",
        "pra cima",
        "estamos juntos",
        "força",
        "não desista",
        "tamo junto",
        "estou com você",
        "meus sentimentos",
        "muita luz",
        "vai dar tudo certo",
        "conte comigo",
        "resiliência",
        "coragem",
        "estamos ao seu lado",
        "justiça",
        "merecido",
        "verdade aparecendo",
        "parabéns pela coragem",
        "exemplo de pessoa",
        "inspirador",
        "inspiração",
        "orgulho",
        "admirável",
        "guerreiro",
        "guerreira",
        "resistência",
        "parabéns",
        "sucesso",
        "você merece",
        "conquista",
        "vitória",
        "brilhante",
        "excelente trabalho",
        "arrasou",
        "mandou bem",
        "orgulho de você",
        "que notícia boa",
        "felicidades",
        "empatia",
        "humanidade",
        "respeito",
        "solidário",
        "solidária",
        "compreensão",
        "acolhimento",
        "conte comigo",
        "forças",
        "sinto muito"
        "estamos com você",
        "meu apoio",
        "total apoio",
        "bravo",
        "magnífico",
        "espetacular",
        "viva",
        "merece muito"
    ]
    return any(word in text.lower() for word in solida_keywords)