def check_solida(text: str) -> bool:
    # apoio geral (ótimo, excelente, maravilhoso)
    solida_keywords = [
        "acolhimento",
        "admiravel",
        "arrasou",
        "bravo",
        "brilhante",
        "compreensao",
        "conquista",
        "conte comigo",
        "coragem",
        "empatia",
        "espetacular",
        "estamos ao seu lado",
        "estamos com voce",
        "estamos juntos",
        "estou com voce",
        "excelente trabalho",
        "exemplo de pessoa",
        "felicidades",
        "forca",
        "forcas",
        "guerreira",
        "guerreiro",
        "humanidade",
        "inspiracao",
        "inspirador",
        "justica",
        "magnifico",
        "mandou bem",
        "merece muito"
        "merecido",
        "meu apoio",
        "meus sentimentos",
        "muita luz",
        "nao desista",
        "orgulho de voce",
        "orgulho",
        "parabens",
        "pra cima",
        "que noticia boa",
        "resiliencia",
        "resistencia",
        "respeito",
        "sinto muito"
        "solidaria",
        "solidario",
        "sucesso",
        "tamo junto",
        "tmj",
        "total apoio",
        "vai dar tudo certo",
        "verdade aparecendo",
        "vitoria",
        "viva"
    ]
    return any(word in text.lower() for word in solida_keywords)